name: Build Backend Executables

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-macos:
    name: Build for macOS
    runs-on: macos-13

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11.9'

      - name: Install Dependencies
        working-directory: Backend
        run: |
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build macOS Binary
        working-directory: Backend
        run: |
          pyinstaller --onefile run.py

      - name: Upload macOS Binary
        uses: actions/upload-artifact@v4
        with:
          name: backend-macos-binary
          path: Backend/dist/*
